// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg3cWBY68n9nwZH7wxdANM9mmXsSfncGM',
    appId: '1:424037308410:web:6fe3c5fd8a474d7fe33643',
    messagingSenderId: '424037308410',
    projectId: 'findmyspot-a693c',
    authDomain: 'findmyspot-a693c.firebaseapp.com',
    storageBucket: 'findmyspot-a693c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN0z-AaYLMhUS17enYtXOev4OS6QqobqI',
    appId: '1:424037308410:android:2ee022b9fed9cf1fe33643',
    messagingSenderId: '424037308410',
    projectId: 'findmyspot-a693c',
    storageBucket: 'findmyspot-a693c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa3FyIIqkya9ILeKshc6jnFetSOqnkua0',
    appId: '1:424037308410:ios:a075fb9f35246c74e33643',
    messagingSenderId: '424037308410',
    projectId: 'findmyspot-a693c',
    storageBucket: 'findmyspot-a693c.firebasestorage.app',
    iosBundleId: 'com.example.parkingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa3FyIIqkya9ILeKshc6jnFetSOqnkua0',
    appId: '1:424037308410:ios:a075fb9f35246c74e33643',
    messagingSenderId: '424037308410',
    projectId: 'findmyspot-a693c',
    storageBucket: 'findmyspot-a693c.firebasestorage.app',
    iosBundleId: 'com.example.parkingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg3cWBY68n9nwZH7wxdANM9mmXsSfncGM',
    appId: '1:424037308410:web:e8fa5caa58f45c87e33643',
    messagingSenderId: '424037308410',
    projectId: 'findmyspot-a693c',
    authDomain: 'findmyspot-a693c.firebaseapp.com',
    storageBucket: 'findmyspot-a693c.firebasestorage.app',
  );
}
